COMPONENT_DEPENDENCIES := 

COMPONENT_NAME := $(CURRENT_COMPONENT)


${DIRS_BUILD}/$(DIRS_LIBRARIES)/$(COMPONENT_NAME)/lib$(COMPONENT_NAME).a:
	@echo "Building component: $(COMPONENT_NAME)"
	@mkdir -p $(@D)