COMPONENT_DEPENDENCIES := bare
COMPONENT_SOURCE_FILES := system.cxx

COMPONENT_NAME := $(CURRENT_COMPONENT)
COMPONENT_DIRECTORY := $(CURRENT_COMPONENT_DIRECTORY)
COMPONENT_TARGET := $(CURRENT_TARGET)
COMPONENT_TARGET_DIRECTORY := $(CURRENT_TARGET_DIRECTORY)


${COMPONENT_TARGET}: $(addprefix $(COMPONENT_DIRECTORY)/, $(COMPONENT_SOURCE_FILES))
	@echo "Building: $@"
	@mkdir -p $(@D)
	$(TOOLCHAIN_CXX) $(CXXFLAGS) -c $< -o $@