CURRENT_DIR = $(CURRENT_INCLUDE_DIR)
BUILD_OBJECT_STARTUP := $(DIRS_BUILD)/$(CURRENT_DIR)/startup.o
STARTUP_FILENAME	:= startup_ch32v203.c

# RULES
$(BUILD_OBJECT_STARTUP): $(CURRENT_DIR)/$(STARTUP_FILENAME)
	@echo "CURRENT DIR STARTUP= $^"
	@mkdir -p $(@D)
	$(TOOLCHAIN_CC) -c $< $(CCFLAGS) -o $@